import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowLeft, Upload } from 'lucide-react';
import { usePassCrewStore } from '../store/passCrewStore';
import { useCustomerAuthStore } from '../store/customerAuthStore';
import { useToastStore } from '../store/toastStore';
import PaymentQRCard from '../components/pass-crew/PaymentQRCard';

export default function PassCrewRequestPage() {
  const { customer } = useCustomerAuthStore(); const { plans, selectedPlan, settings, activeRequest, loadLandingData, loadSettings, loadMyStatus, selectPlan, submitRequest, uploadReceiptForRequest } = usePassCrewStore();
  const [file,setFile]=useState<File|null>(null); const [busy,setBusy]=useState(false); const addToast=useToastStore(s=>s.addToast); const navigate=useNavigate();
  useEffect(()=>{ loadLandingData(); loadSettings(); },[loadLandingData,loadSettings]); useEffect(()=>{ if(customer) loadMyStatus(customer.id); },[customer,loadMyStatus]);
  const generate=async()=>{ if(!selectedPlan)return; setBusy(true); try{await submitRequest(selectedPlan.id);addToast('Solicitud creada. Ahora sube tu comprobante.','success');}catch(e){addToast(e instanceof Error?e.message:'No se pudo crear la solicitud','error');}finally{setBusy(false);}};
  const send=async()=>{if(!activeRequest||!file)return;setBusy(true);try{await uploadReceiptForRequest(activeRequest.id,file);addToast('Comprobante enviado para revisión','success');navigate('/pass-crew/status');}catch(e){addToast(e instanceof Error?e.message:'No se pudo enviar el comprobante','error');}finally{setBusy(false);}};
  return <div className="min-h-screen bg-[#f5f5f2] px-4 pb-20 pt-28"><div className="mx-auto max-w-3xl"><Link to="/pass-crew" className="mb-8 inline-flex items-center gap-2 text-xs uppercase tracking-[.2em] text-black/50"><ArrowLeft className="h-4 w-4"/>PASS Crew</Link><h1 className="text-4xl font-black uppercase tracking-[-.04em] sm:text-6xl">Solicitar membresía</h1><p className="mt-3 text-sm text-black/50">La membresía se activa después de que PASS revise y apruebe el comprobante.</p>
    {!activeRequest ? <div className="mt-10 space-y-5"><div className="grid gap-3 sm:grid-cols-2">{plans.map(plan=><button key={plan.id} onClick={()=>selectPlan(plan)} className={`p-6 text-left ${selectedPlan?.id===plan.id?'border-2 border-black bg-white':'border border-black/15 bg-white'}`}><p className="text-xs uppercase tracking-[.25em] text-black/45">{plan.name}</p><p className="mt-4 text-3xl font-black">Bs {Number(plan.price).toFixed(0)}</p><p className="mt-1 text-sm text-black/50">{plan.duration_months} meses</p></button>)}</div><button onClick={generate} disabled={!selectedPlan||busy} className="w-full bg-black py-4 text-xs font-bold uppercase tracking-[.2em] text-white disabled:bg-black/30">{busy?'Creando…':'Continuar con el pago'}</button></div> : <div className="mt-10 space-y-5"><div className="bg-white p-6"><p className="text-xs uppercase tracking-[.2em] text-black/40">Solicitud {activeRequest.request_number}</p><p className="mt-3 text-xl font-bold">{activeRequest.plan_name_snapshot} · Bs {Number(activeRequest.price_snapshot).toFixed(0)}</p><p className="mt-1 text-sm text-black/50">{activeRequest.duration_months_snapshot} meses</p></div>{activeRequest.status==='draft' ? <><PaymentQRCard settings={settings}/><div className="bg-white p-6"><label className="block text-xs font-bold uppercase tracking-[.2em]">Comprobante</label><input className="mt-4 block w-full text-sm" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><button onClick={send} disabled={!file||busy} className="mt-5 inline-flex w-full items-center justify-center gap-2 bg-black py-4 text-xs font-bold uppercase tracking-[.2em] text-white disabled:bg-black/30"><Upload className="h-4 w-4"/>{busy?'Enviando…':'Enviar a revisión'}</button></div></> : <div className="bg-white p-6 text-sm">Tu comprobante ya está en revisión. <Link className="underline" to="/pass-crew/status">Ver estado</Link></div>}</div>}
  </div></div>;
}
