import { useEffect, useState } from 'react';
import { ArrowRight, Crown, Lock } from 'lucide-react';
import { Link } from 'react-router-dom';
import { passCrewService } from '../services/passCrewService';
import type { CrewBenefit, CrewPlan } from '../types';

export default function RewardsCatalogPage() {
  const [plans, setPlans] = useState<CrewPlan[]>([]);
  const [benefits, setBenefits] = useState<CrewBenefit[]>([]);
  useEffect(() => { passCrewService.getActivePlans().then(setPlans).catch(() => setPlans([])); passCrewService.getCrewBenefits().then(setBenefits).catch(() => setBenefits([])); }, []);
  return <main className="min-h-[75vh] bg-[#0e0e0d] px-5 py-20 text-white sm:px-8 sm:py-28"><div className="mx-auto max-w-6xl"><div className="max-w-2xl"><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.3em] text-champagne"><Crown className="h-4 w-4"/> PASS Crew / Recompensas</p><h1 className="mt-5 text-5xl font-black uppercase leading-[.86] tracking-[-.07em] sm:text-8xl">Catálogo de<br/>recompensas.</h1><p className="mt-7 max-w-lg text-sm leading-6 text-white/55">Explora los beneficios publicados por PASS. Las recompensas visibles dependen de la configuración vigente de cada plan.</p></div><div className="mt-16 border-t border-white/10 pt-8"><div className="mb-8 flex items-end justify-between"><div><p className="text-[10px] uppercase tracking-[.25em] text-white/35">Publicadas</p><h2 className="mt-2 text-2xl font-bold">Beneficios disponibles</h2></div><span className="text-xs text-white/35">{benefits.length} publicados</span></div>{benefits.length ? <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{benefits.map((benefit) => <article key={benefit.id} className="flex min-h-52 flex-col justify-between border border-white/10 bg-white/[.025] p-6 transition-colors hover:border-champagne/50"><div><p className="text-[10px] uppercase tracking-[.2em] text-champagne">{benefit.benefit_type.replaceAll('_', ' ')}</p><h3 className="mt-4 text-xl font-bold">{benefit.name}</h3>{benefit.description && <p className="mt-3 text-sm leading-5 text-white/45">{benefit.description}</p>}</div><div className="mt-8 flex items-center justify-between border-t border-white/10 pt-4"><span className="text-[10px] uppercase tracking-[.16em] text-white/35">Según plan</span><Lock className="h-4 w-4 text-champagne"/></div></article>)}</div> : <div className="border border-dashed border-white/15 px-6 py-16 text-center"><p className="text-lg font-semibold">El catálogo está tomando forma.</p><p className="mt-2 text-sm text-white/45">PASS publicará aquí sus recompensas cuando estén configuradas.</p></div>}</div><div className="mt-16 flex flex-col items-start justify-between gap-6 border-t border-white/10 pt-8 sm:flex-row sm:items-center"><div><p className="text-sm text-white/55">¿Quieres acceder a beneficios exclusivos?</p><p className="mt-1 text-xs text-white/35">Planes activos: {plans.map(plan => `${plan.name} · Bs ${Number(plan.price).toFixed(0)}`).join(' / ') || 'Próximamente'}</p></div><Link to="/pass-crew" className="inline-flex items-center gap-3 bg-champagne px-6 py-4 text-[10px] font-bold uppercase tracking-[.18em] text-black">Conocer PASS Crew <ArrowRight className="h-4 w-4"/></Link></div></div></main>;
}
